baseURL = "https://www.sedhyd.org/2019/"
languageCode = "en-us"
title = "SEDHYD 2019 Conference"
theme = "ananke"
googleAnalytics = "UA-123026999-1"
[menu]

  [[menu.main]]
    identifier = "Home"
    name = "Home"
    pre = "<i class='fa fa-heart'></i>"
    url = "/"
    weight = -110

  [[menu.main]]
    name = "Call for Papers"
    pre = "<i class='fa fa-road'></i>"
    url = "/files/SEDHYD2019-CallForPapers-2018-06-29.pdf"
    weight = -100

  [[menu.main]]
    name = "Venue / Hotel Reservation"
    pre = "<i class='fa fa-road'></i>"
    url = "/venue/"
    weight = -100
  [[menu.main]]
    name = "Registration"
    pre = "<i class='fa fa-road'></i>"
    url = "/registration/"
    weight = -100

[[menu.main]]
    name = "Contact Us"
    pre = "<i class='fa fa-road'></i>"
    url = "/contact/"
    weight = -90

featured_image='/images/2015-04-SEDHYD-Reno-085.JPG'